name: Generate SBOM in CDX json and VA

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM in CycloneDX format
        run: syft /src/main/ -o cyclonedx-json=log4shell-vulnerable-app-CDX.json
        #run: syft ./ -o cyclonedx-json=log4shell-vulnerable-app-CDX.json
        #working-directory: log4shell-vulnerable-app/src/main/
        
      - name: Generate SBOM in console
        run: syft .
        
      - name: Upload SBOM as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: SBOM
          path: log4shell-vulnerable-app-CDX.json
      
      - name: Commit SBOM to repository
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add log4shell-vulnerable-app-CDX.json
          git commit -m "Add SBOM for log4shell-vulnerable-app"
          git push

  vulnerability-analysis:
    needs: generate-sbom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download SBOM artifact
        uses: actions/download-artifact@v2
        with:
          name: SBOM

      - name: Install Grype
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run vulnerability analysis
        run: grype sbom:log4shell-vulnerable-app-CDX.json -o table
