name: Generate SBOM in CDX json and VA

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM in CycloneDX format
        run: syft packages dir:/path/to/project -o cyclonedx-json=sbom.json

      - name: Upload SBOM as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: SBOM
          path: sbom.json

  vulnerability-analysis:
    needs: generate-sbom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download SBOM artifact
        uses: actions/download-artifact@v2
        with:
          name: SBOM

      - name: Install Grype
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run vulnerability analysis
        run: grype sbom:sbom.json -o table
